@Server_HostAddress = http://localhost:32778

GET {{Server_HostAddress}}/todos/
Accept: application/json

###

GET {{Server_HostAddress}}/todos/1
Accept: application/json

###

POST  {{Server_HostAddress}}/user/register
Content-Type: application/json 
{ 
  "Email": "user@example.com"
}

###