@Server_HostAddress = http://localhost:5021
//@Server_HostAddress = http://localhost:32783
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkd2EiLCJqdGkiOiJjZTdlNDMxYy00NjEwLTQxYjctOGQ0ZC02OWU4OTVkYWZmYjgiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJwaG9uZV9udW1iZXIiOiIxMjM0NTY3ODkxMDMiLCJuYW1laWQiOiIwMTk0ZDBlZi1jNTZjLTcxMmUtYjUwNy01YjU0MGY2Mzk3NDkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJEcml2ZXIiLCJlbWFpbF92ZXJpZmllZCI6IlRydWUiLCJDcmVhdGVkVGlja3MiOiI2Mzg3NDI2ODk2MjE1NjQzODMiLCJVcGRhdGVkVGlja3MiOiI2Mzg4MDY3NjUxMDk3Mjk4MTciLCJVc2VyVXBkYXRlZElkIjoiMDE5NGQwZWYtYzU2Yy03MTJlLWI1MDctNWI1NDBmNjM5NzQ5IiwiSXNEZWxldGUiOiJGYWxzZSIsImV4cCI6MTc0NTY4NDUxMCwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0VXNlcnMifQ._ZPnVBishimbSx0M1PhTnvJ7uWpVEKoMqQmaryJ46P4

POST {{Server_HostAddress}}/{{server_user}}/login
Content-Type: application/json 

{ 
    "Email": "user@example.com",
    "Password": "Password1!",
    "RememberMe": 1
}
###

GET {{Server_HostAddress}}/inventory/empty_products
Accept: application/json

###
GET {{Server_HostAddress}}/inventory/day/7329b642-feb2-4931-944a-c4b1616351de
Accept: application/json
Authorization: bearer {{token}}

###
GET {{Server_HostAddress}}/inventory/day?selectedDateString=30.09.2023&driverGuid=ae86aaeb-1080-4ae2-9226-62cf3a042ca8
Accept: application/json
Authorization: bearer {{token}}

###
GET {{Server_HostAddress}}/inventory/days?to=638684857021318544&from=638670998602305712&userid=ae86aaeb-1080-4ae2-9226-62cf3a042ca8&userid=ae86aaeb-1080-4ae2-9226-62cf3a042ca8
Accept: application/json
Authorization: bearer {{token}}

### 


GET {{Server_HostAddress}}/todos/
Accept: application/json
Authorization: bearer {{token}}
###
GET {{Server_HostAddress}}/todos/1
Accept: application/json

###


POST  {{Server_HostAddress}}/user/register
Content-Type: application/json 

{ 
    "Email": "user@example.com",
    "Name": "Name",
    "Description": "Description",
    "PhoneNumber": "123456789",
    "Password": "Password1!"
}

###
GET {{Server_HostAddress}}/user/confirm_email/57179
Accept: application/json

###
GET {{Server_HostAddress}}/user/logout/
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{Server_HostAddress}}/user/refresh_token
Authorization: Bearer {{token}}

### 
POST {{Server_HostAddress}}/user/edit
Authorization: Bearer {{token}}
Content-Type: application/json 

{
    "Email": "user@example113.com",
    "Name": "osiem3",
    "Description": "brak123",
    "PhoneNumber": "123456789103",
    "UserType":2
}

###
GET {{Server_HostAddress}}/user/0194d0ef-c56c-712e-b507-5b540f639749
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{Server_HostAddress}}/user/reset_password_email/user@example.com
Accept: application/json

###
GET {{Server_HostAddress}}/user/reset_password/74091
Accept: application/json

###
GET {{Server_HostAddress}}/user/reset_password/74091/Password1!
Accept: application/json

###

